name: CI
on: [ push ]
jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Schema Validation of Areas
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: validate-areas
      - name: PHP Composer
        uses: php-actions/composer@v5
        with:
          php_version: 8.0
      - name: PHPUnit tests
        uses: php-actions/phpunit@v3
        with:
          php_version: 8.0
